print('hi')
july<-read.csv("C:/Users/daani/cyclist_bike_share/divvy-tripdata/202007-divvy-tripdata.csv")
august<-read.csv("C:/Users/daani/cyclist_bike_share/divvy-tripdata/202008-divvy-tripdata.csv")
september<-read.csv("C:/Users/daani/cyclist_bike_share/divvy-tripdata/202009-divvy-tripdata.csv")
october<-read.csv("C:/Users/daani/cyclist_bike_share/divvy-tripdata/202010-divvy-tripdata.csv")
november<-read.csv("C:/Users/daani/cyclist_bike_share/divvy-tripdata/202011-divvy-tripdata.csv")
december<-read.csv("C:/Users/daani/cyclist_bike_share/divvy-tripdata/202012-divvy-tripdata.csv")
january<-read.csv("C:/Users/daani/cyclist_bike_share/divvy-tripdata/202101-divvy-tripdata.csv")
february<-read.csv("C:/Users/daani/cyclist_bike_share/divvy-tripdata/202102-divvy-tripdata.csv")
march<-read.csv("C:/Users/daani/cyclist_bike_share/divvy-tripdata/202103-divvy-tripdata.csv")
april<-read.csv("C:/Users/daani/cyclist_bike_share/divvy-tripdata/202104-divvy-tripdata.csv")
may<-read.csv("C:/Users/daani/cyclist_bike_share/divvy-tripdata/202105-divvy-tripdata.csv")
june<-read.csv("C:/Users/daani/cyclist_bike_share/divvy-tripdata/202106-divvy-tripdata.csv")
head(august)
class(july)
tripdata <- bind_rows(july, august, september, october, november, december, january, february, march, april, may, june)
a <- rbind(july, august)
b <- rbind(a, september)
c <- rbind(b, october)
d <- rbind(c, november)
e <- rbind(d, december)
f <- rbind(e, january)
g <- rbind(f, february)
h <- rbind(g, march)
i <- rbind(h, april)
j <- rbind(i, may)
tripdata <- rbind(j, june)

library(tidyr)
df <- na.omit(tripdata)
